version: '3.3'

volumes:
    redis-data:

services:
    redis:
        image: redis:latest
        volumes:
            - redis-data:/data
        expose:
            - 6379
        ports:
            - 6379:6379